version: '2'
services:
    filter1-app:
        image: filter1
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://filter1-postgresql:5432/filter1
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    filter1-postgresql:
        extends:
            file: postgresql.yml
            service: filter1-postgresql
